In [1]:
import numpy as np

In [2]:
a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
print("A= ")
print(a)
a_Transpose = a.transpose()
print("Transpose of A= ")
print(a_Transpose) 

A= 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Transpose of A= 
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [3]:
b = ([[11,12,13],
      [14,15,16],
      [17,18,19]])

c = a+b
print(c) #Sum of 2 matrices


[[12 14 16]
 [18 20 22]
 [24 26 28]]
