In [1]:
import numpy as np

In [2]:
a = np.arange(0,18)
a = a.reshape(6,3)
print(a)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]


In [3]:
b = np.arange(20,38)
b = b.reshape(6,3)
print(b)

[[20 21 22]
 [23 24 25]
 [26 27 28]
 [29 30 31]
 [32 33 34]
 [35 36 37]]


In [ ]:
sum = a+b
print(sum)